symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository

    # Durée de validité du lien (1 heure)
    lifetime: 3600

    # IMPORTANT :
    # Désactive le blocage multiple trop agressif
    # mais garde la sécurité minimale
    throttle_limit: 60